site_name: Optical Intellegence

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - About: index.md
  - Articles:
    - blog/index.md
  - Contact: contact.md

plugins:
  - search
  - blog:
      post_dir: blog/posts
      archive: true
      categories: true